name: check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4

      - name: install
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      
      - name: install libtorch
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
          unzip libtorch-shared-with-deps-latest.zip

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon check
        run: moon check --target native

      - name: moon info
        run: |
          moon info --target native
          git diff --exit-code
      
      - name: build
        run:  bash .github/workflows/build.sh

      - name: Set ulimit and run bash test.sh
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          ulimit -s 8176
           bash .github/workflows/test.sh

  typo-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_COLOR: 1
      TYPOS_VERSION: v1.19.0
    steps:
      - name: download typos
        run: curl -LsSf https://github.com/crate-ci/typos/releases/download/$TYPOS_VERSION/typos-$TYPOS_VERSION-x86_64-unknown-linux-musl.tar.gz | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: check typos
        run: typos

  nightly-check:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s 'nightly'
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install libtorch
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
          unzip libtorch-shared-with-deps-latest.zip

        env:
          MOONBIT_INSTALL_VERSION: nightly

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon check
        run: moon check 

      - name: build
        run:  bash .github/workflows/build.sh

      - name: Set ulimit and run bash test.sh
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          ulimit -s 8176
           bash .github/workflows/test.sh

  moon-json-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check `moon.*.json` format
        shell: bash
        run: |
          _passed=0;
          for f in $(find . -type f -name "moon.*.json"); do
            if ! jq '.' $f > /dev/null; then
              echo $f;
              _passed=1;
            fi
          done
          (exit $_passed)
